server:
  port: 8888

spring:
  application:
    name: ss-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dhiegoluz/ss-config-server-repo
          default-label: main
        
ss:
  serviceRegistry:
    username: serviceregistry
    password: 'ericsson123'

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ss.serviceRegistry.username}:${ss.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost