server:
  port: 8888

spring:
  application:
    name: ss-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/dhiegoluz/ss-config-server-repo
          default-label: main
        
ss:
  serviceRegistry:
    username: serviceregistry
    password: 'ericsson123'
  auth:
    jwtSecret: y$B&E)H@MbQeThWmZq4t7w!z%C*F-JaNdRfUjXn2r5u8x/A?D(G+KbPeShVmYp3s
    jwtExpirationMs: 14400000
  

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://${ss.serviceRegistry.username}:${ss.serviceRegistry.password}@localhost:8761/eureka'
  instance:
    hostname: localhost